apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  selector:
    app: django
  type: NodePort  # Change from LoadBalancer to NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007  # You can specify or let Kubernetes assign it


